export const ActionTypes = {

    FETCH_PRODUCTS : 'FETCH_PRODUCTS',    
    FETCH_ERROR : 'FETCH_ERROR',
    FETCH_REQUEST_STARTED : 'FETCH_REQUEST_STARTED',
    FETCHED_DATA : 'FETCHED_DATA',
    FETCHED_MORE_DATA: 'FETCHED_MORE_DATA',
    SET_QUERY: 'SET_QUERY',
}
